In [2]:
import numpy as np

In [22]:
a =np.array([5, 8, 12, 20, 7, 3])

In [23]:
print(a.sum())

55


In [25]:
print(a[a>7])

[ 8 12 20]


In [26]:
print(a.mean())

9.166666666666666


In [30]:
b = np.arange(9).reshape((3,3))
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
print(b[1])

[3 4 5]


In [31]:
print(b[:,2])

[2 5 8]


In [32]:
print(b*5)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]


In [42]:
print(b.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [44]:
print(b.sum(axis=1))

[ 3 12 21]


In [46]:
print(b.sum(axis=0))

[ 9 12 15]


In [52]:
b = np.where(b>4,0,b)
print(b)

[[0 1 2]
 [3 4 0]
 [0 0 0]]


Завдання 1: Normalization (масштабування)

In [57]:
arr = np.array([15, 25, 5, 35, 10])
arrMax = arr.max()
arrMin = arr.min()
normalized = (arr - arrMin)/(arrMax -arrMin)
print(normalized)

[0.33333333 0.66666667 0.         1.         0.16666667]


Завдання 2: One-Hot Encoding вручну

In [65]:
labels = np.array([0, 1, 2, 1, 0])
classes = np.max(labels)+1
onehot = np.zeros((labels.size,classes))
onehot[np.arange(labels.size), labels] = 1
print(onehot)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


Завдання 3: Створення діагональної матриці

In [72]:
a = np.array([1, 2, 3])
diag_matrix = np.diag(a)
print(diag_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


 Завдання 4: Обнулити всі значення на головній діагоналі матриці

In [83]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
for i in range(m.shape[0]):
    for j in range(m.shape[0]):
        if i==j:
            m[i,j]=0
print(m)

[[0 2 3]
 [4 0 6]
 [7 8 0]]


In [87]:
A = np.random.randint(0, 10, (4, 4))
A_sym = (A + A.T) / 2
print(A_sym)

[[0.  5.5 6.5 6. ]
 [5.5 0.  5.  0.5]
 [6.5 5.  6.  6. ]
 [6.  0.5 6.  8. ]]


In [88]:
chessboard = np.zeros((8, 8), dtype=int)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1
print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [2]:
import numpy as np
arr = np.array([15, 25, 5, 35, 10])

In [11]:
arrNorm = -(arr-arr.min())/(arr.min()-arr.max())
print(np.sort(arrNorm))

[-0.          0.16666667  0.33333333  0.66666667  1.        ]


In [14]:
board = np.zeros((8, 8), dtype=int)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 1:
            board[i, j] = 1
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Підрахунок локальних максимумів у матриці

In [36]:
mat = np.array([
    [3, 5, 2],
    [4, 7, 1],
    [6, 8, 9]
])
print()
right = np.pad(mat[:, :-1],  ((0,0),(1,0)), mode='constant')
print(right)

mask = mat>right
resMatrix = mask[:,1:]
print(resMatrix)
print("\nКількість локальних максимумів:", np.sum(resMatrix))


[[0 3 5]
 [0 4 7]
 [0 6 8]]
[[ True False]
 [ True False]
 [ True  True]]

Кількість локальних максимумів: 4


кількість зростаючих рядків

In [42]:
mat = np.array([
    [1, 2, 3],
    [5, 4, 6],
    [7, 8, 9]
])
res = np.diff(mat, axis=1)
mask = res>0
mask = np.all(mask, axis=1)
print("\nкількість зростаючих рядків:", np.sum(mask))


кількість зростаючих рядків: 2
